const icons = {
  /****** UTILITY CLICKABLES ******/
  addToPlaylist: "mdi:playlist-plus",
  bookmark: "carbon:bookmark-add",
  bookmarked: "carbon:bookmark-filled",
  clock: "heroicons-solid:clock",
  close: "fa-solid:times",
  closeFilled: "jam:close-circle-f",
  delete: "icomoon-free:bin",
  editPlaylist: "mdi:playlist-edit",
  explore: "ic:baseline-explore",
  eye: "fa6-solid:eye",
  eyeSlash: "fa6-solid:eye-slash",
  filter: "ant-design:control-filled",
  heart: "fa-regular:heart",
  heartFilled: "fa:heart",
  history: "fa:history",
  home: "fa:home",
  like: "bx:like",
  liked: "bxs:like",
  login: "entypo:login",
  logout: "mdi:logout",
  menu: "ion:ellipsis-vertical-circle-sharp",
  play: "fa6-brands:google-play",
  playlist: "ic:sharp-playlist-play",
  playlistIcon: "bi:collection-play-fill",
  plus: "fa:plus",
  settings: "fa-solid:cog",
  share: "ci:share",
  share2: "fa-solid:share",
  user: "fa-solid:user",
  views: "carbon:view-filled",

  /****** THEMED ******/
  danger: "fa:ban",
  info: "fa-solid:info-circle",
  success: "fa-solid:check-circle",
  warning: "fa:exclamation-triangle",

  /****** BRANDS ******/
  facebook: "fa-brands:facebook-f",
  github: "fa-brands:github",
  instagram: "fa6-brands:instagram",
  linkedin: "fa-brands:linkedin-in",
  medium: "fa-brands:medium-m",
  twitter: "fa-brands:twitter",
  whatsapp: "fa6-brands:whatsapp",
};

export { icons };
